language: node_js
node_js:
  - "14"

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn lint
  - yarn build

after_success:
  - mkdir -p public_html
  - mv build/* public_html/
  - find public_html -type f -exec curl -v --ftp-pasv -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://$FTP_HOST/mail.emailfy.io/{} \;
