name: Sync GitHub Issues

on:
  workflow_dispatch:
  
permissions:
  issues: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      
      - name: Install Yarn
        run: npm install -g yarn
        
      - name: Install dependencies with Yarn
        run: yarn add @octokit/rest @octokit/request
      
      - name: Sync issues and add to project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: node .github/scripts/sync-issues.js
